# @package _global_

optim: 
  lr: 5e-4   
  epochs: 500 # 192 steps/epochs on Arts -> 3125 epochs = 600k steps, adapt to category.

centroids: 
  kmeans_init: false    

model: 
  type: hyperbolic
  layers: [1024, 512, 256, 16]
  c: 2.0

loss: 
  reconstruction_weight: 1.0
  quantization_weight: 1.0
  contrastive_weight: 0.001
  tau: 2 
  bias: -8
  freeze_tau: false 
  freeze_bias: false
  sequence_length: 20