defaults: 
- _self_
- paths
- disable_hydra_dirs

data:
  category: Beauty
  emb_method: sentence-t5-xl

model:
  type: hyperbolic  # euclidean # CHANGED

paths:
  ckpt_dir: outputs/checkpoints/cosette

marker: null