defaults: 
- _self_
- cosette: default # Will override model, data, ...
- paths
- disable_hydra_dirs

data:
  category: Beauty
  emb_method: sentence-t5-xl

model:
  type: euclidean  # euclidean

paths:
  ckpt_dir: outputs/checkpoints/cosette

marker: null