defaults:
- _self_
- experiment: ??? # Will override model, data, ...
- disable_hydra_dirs
- paths

# task name, determines output directory path
task_name: ??? # Overriden by experiment selection
date: ${now:%y%m%d}_${now:%H%M%S}
seed: 0

trainer: 
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: auto
  precision: bf16-mixed
  check_val_every_n_epoch: null
  val_check_interval: 10_000
  limit_val_batches: 1000 # Reduce for faster (approximate) validation
  max_steps: 81_000 # Overriden by experiment selection
  limit_train_batches: ${eval:'${data.datasets.total_len} // ${data.datamodule.train_batch_size}'}
  # CALLBACKS
  callbacks: 
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: -1
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
    log_momentum: False
    log_weight_decay: True
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${paths.model_folder_tplt}/${task_name}_${date}
    filename: "checkpoint"
    save_top_k: 1
    monitor: valid/${data.datasets.category}/HR@10
    mode: max
    save_weights_only: True
  - _target_: src.utils.callbacks.SaveConfigCallback
  # LOGGING 
  logger:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    name: null # Overriden with run name in code
    project: ${paths.wandb_project_name}
    entity: ${paths.wandb_entity}
    mode: ${paths.wandb_mode}

model: # Lightning Module for Training 
  _target_: src.lightning_module.LitModule
  net: null # Overriden by experiment selection
  mode: ??? # Overriden by experiment selection
  optimizer: 
    _target_: torch.optim.AdamW
    _partial_: true
    fused: true
    lr: ??? # Overriden by experiment selection
    weight_decay: ??? # Overriden by experiment selection
  scheduler: 
    _target_: src.utils.scheduler.CosineScheduler
    _partial_: true
    warmup_steps: ???
    cosine_steps: ${eval:'${trainer.max_steps} - ${model.scheduler.warmup_steps}'}

data: 
  datasets: 
    _target_: src.data.datasets.make_datasets
    category: Video_Games
    total_len: ${eval:'${trainer.max_steps}*${data.datamodule.train_batch_size}'}
    emb_id: ??? # Overriden by experiment selection
    quant_id: ??? # Overriden by experiment selection
    num_workers: 4 # Depends on the machine
    prepro_cfg: 
      _cls_: ??? # Overriden by experiment selection
      crop_length: 50
      augment: timewise_shuffle
  datamodule:
    _target_: src.data.datamodule.RecDataModule
    train_batch_size: 256
    valid_batch_size: 256



    